name: Bug Report
description: Report a bug with POE Searcher
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: Which version of POE Searcher are you using?
      placeholder: "e.g., 0.2.0"
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Brave
        - Edge
        - Other Chromium-based browser
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Copy item text '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: item-text
    attributes:
      label: Item Text (if applicable)
      description: The POE item text that caused the issue
      placeholder: Paste the item text here
      render: text

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Screenshots, console errors, etc.