name: Feature Request
description: Suggest a new feature for POE Searcher
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear description of what you want to happen
      placeholder: Describe the feature you'd like to see
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case and why this feature would be helpful
      placeholder: How would this feature improve your POE trading experience?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Alternative solutions you've considered
      placeholder: Any alternative approaches or workarounds?

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the feature request
      placeholder: Mockups, examples, related issues, etc.