name: CI

on:
  pull_request:
    branches:
      - '*'
    branches-ignore:
      - 'main'
    paths:
      - 'src/**'
      - 'package.json'
      - '.changeset/**'
      - '.github/workflows/**'
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'package.json'
      - '.changeset/**'
      - '.github/workflows/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

  typecheck:
    name: TypeScript Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run TypeScript Check
        run: npm run typecheck

  build:
    name: Build Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Extension
        run: npm run build

      - name: Package Extension
        run: npm run package

      - name: Verify Package Created
        run: |
          echo "Checking for poesearcher.zip..."
          ls -la *.zip || echo "No zip files in root"
          if [ -f "poesearcher.zip" ]; then
            echo "✅ poesearcher.zip exists"
            echo "File size: $(ls -lh poesearcher.zip | awk '{print $5}')"
          else
            echo "❌ poesearcher.zip not found!"
            exit 1
          fi

      - name: Upload Build Artifact (PR only)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: poesearcher-pr-${{ github.event.number }}
          path: poesearcher.zip
          retention-days: 7